### PR TITLE
Update build to Go 1.10.8 so it completes successfully again

### PR DESCRIPTION
**Pull request by tianon**
See https://pkgs.alpinelinux.org/package/v3.8/community/x86_64/go, which has since updated to Go 1.10.8. :+1:

### CODE REVIEW

**Comment by tianon** [comment]
Friendly ping @justincormack :heart:

**Comment by tianon** [comment]
Do we need someone else to take a look at this too? (I don't have merge access here, and it's my understanding that you're the maintainer here now. :sweat_smile: :heart:)

**Comment by thaJeztah** [comment]
Should we update to alpine 3.10 and Go 1.12.8 ? https://github.com/theupdateframework/notary/pull/1485

**Comment by justincormack** [comment]
@thaJeztah ah ok, yeah can you open a new PR, let me merge this anyway.

**Pull request merged**
