### PR TITLE
Build via multi-stage, update to Go 1.19, Alpine 3.16

### PR DESCRIPTION
**Pull request by tianon**
This is possible now thanks to https://github.com/docker-library/bashbrew/pull/43 -- there are some more dependencies before we can take this all the way linked from https://github.com/docker-library/bashbrew/pull/43#issuecomment-1278331278, but we're close enough that we can start testing at this level. :+1:

### CODE REVIEW

**Comment by tianon** [comment]
Heh, at least #29 works to successfully catch the bug!  I guess we need a new Notary release before we can actually do this? :grimacing:

**Comment by tianon** [comment]
Welp, apparently I don't understand https://github.com/notaryproject/notary/issues/1602 as well as I thought I did because that manual cherry-pick of the jose2go module update didn't fix the failing tests. :see_no_evil:

**Comment by jonnystoten** [comment]
We might also need to cherry-pick notaryproject/notary#1635 for this to work on Go 1.17+. Hopefully we'll make a new notary release soon which will include all of these fixes!

**Comment by tianon** [comment]
Dang, that was an easy one to cherry-pick :sweat_smile: (and it looks like it worked! :metal:)

Do you think these changes are pretty reasonable for us to backport into new builds of the older release this way?  Do you have any objectionary thoughts on the PR in general? :innocent:

**Comment by jonnystoten** [comment]
Awesome, glad that was painless :tada:

> Do you think these changes are pretty reasonable for us to backport into new builds of the older release this way?

I'm not sure, I think I'll defer to you on that! Do we often backport these kind of changes for old releases, or is notary unique? I think these changes are pretty harmless but I guess it could be confusing for a user if, say, the official image works and the release from notary does not.

Hopefully we can have a notary release this week so it might be better to wait for that, but I appreciate we've been saying it will happen soon for a long time! :grimacing: 

My only other thought on this PR is that it might be nice to have a single Dockerfile with three stages, one that does the build step, and then two more stages for the server and signer, each of which just copies over the appropriate binary. This way we wouldn't need to duplicate the build step. I'm not sure if this is possible with the rest of the build pipeline though, and definitely not for this PR!

**Comment by yosifkit** [comment]
> Dockerfile with three stages

The Official Images build pipeline does not support a `--target`, so it would only be able to push the final stage.

**Comment by tianon** [comment]
Yeah, with only two files it should be pretty easy to keep them in sync, but templating would be my recommended solution if we want something more explicit. :+1:

Given "Notary" doesn't release binaries, this is probably fine for us to release, but if you really do believe a new release is imminent I don't see a lot of damage in waiting instead. :smile:

**Comment by tianon** [comment]
Alright, let's do it! :smile:

**Pull request merged**
