### PR TITLE
Bump Golang and Alpine version

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Review by whalelines — COMMENTED** [review]
Have the results of these changes been tested?

**Review by tianon-sso — APPROVED** [review]

**Comment by tianon-sso** [comment]
Yes, there's a smoke test in this repository that runs the full upstream test suite and some basic signing flows with Docker-in-Docker: https://github.com/docker/notary-official-images/blob/d1a94cf525b59aa7452a436d7cdc3d65f2a64fd8/.test/test.sh

**Review by tianon — APPROVED** [review]
Approving here too, just in case this account has merge access :eyes:

**Comment by tianon** [comment]
I've opened an updated alternative to this in https://github.com/docker/notary-official-images/pull/38

**Pull request closed without merging**
